environment: 'snakepac' # 'snakepac' or other when implemented
logging: True

snakepac:
  num_episodes: 100
  num_simulations: 100
  I_t: 10
  batch_size: 32
  world_length: 10
  seed: 42
  uMCTS:
    num_searches: 20
    max_depth: 8
    ucb_constant: 1.0
    discount_factor: 0.95
  
  network:
    iteration: ""
    state_window: 4
    representation:
    - type: linear
      in_features: "" # Will be set by the environment
      out_features: "dont know yet"
      activation: relu
    - type: linear
      in_features: 128
      out_features: 64

    prediction:
      - type: linear
        in_features: 64
        out_features: 64
        activation: relu
      - type: linear
        in_features: 64
        out_features: 10

    dynamics:
      - type: linear
        in_features: 68
        out_features: 128
        activation: relu
      - type: linear
        in_features: 128
        out_features: 64

  

riverraid:
  num_episodes: 100
  num_simulations: 100
  training_interval: 10
  batch_size: 32

  skip_frames: 4
  action_frames: 4
  mcts:
    num_searches: 50
    max_depth: 10
    ucb_constant: 1.0
    discount_factor: 0.95

logging:

network:
  # for snakepac
  iteration: ""
  representation:
  - type: linear
    in_features: "" # Will be set by the environment
    out_features: 
    activation: relu
  - type: linear
    in_features: 128
    out_features: 64

  prediction:
    - type: linear
      in_features: 64
      out_features: 64
      activation: relu
    - type: linear
      in_features: 64
      out_features: 10

  dynamics:
    - type: linear
      in_features: 68
      out_features: 128
      activation: relu
    - type: linear
      in_features: 128
      out_features: 64
