training:
  environment: 'snakepac' # 'snakepac' or other when implemented
  logging: True

snakepac:
  world_length: 10
  seed: 42

mcts:
  num_simulations: 100
  max_depth: 10
  ucb_constant: 1.0
  discount_factor: 0.95

logging:

network:
  iteration: ""
  representation:
  - type: linear
    in_features: 64
    out_features: 128
    activation: relu
  - type: linear
    in_features: 128
    out_features: 64

  prediction:
    - type: linear
      in_features: 64
      out_features: 64
      activation: relu
    - type: linear
      in_features: 64
      out_features: 10

  dynamics:
    - type: linear
      in_features: 68
      out_features: 128
      activation: relu
    - type: linear
      in_features: 128
      out_features: 64
