environment: 'snakepac' # 'snakepac' or other when implemented
logging: True

snakepac:
  num_episodes: 100
  num_episode_step: 50
  training_interval: 20
  history_length: 20
  num_simulations: 100
  I_t: 10
  batch_size: 32
  world_length: 10
  seed: 42
  action_space: 2
  uMCTS:
    num_searches: 20
    max_depth: 8
    ucb_constant: 1.0
    discount_factor: 0.95
  
  network:
    iteration: ""
    state_window: 4
    hidden_state_size: 16
    representation:
    - type: linear
      in_features: 44 # World length * window size + 4 (corresponding actions)
      out_features: 128
      activation: relu
    - type: linear
      in_features: 128
      out_features: 64
    - type: linear
      in_features: 64
      out_features: ${{snakepac.network.hidden_state_size}}

    prediction:
      - type: linear
        in_features: ${{snakepac.network.hidden_state_size}}
        out_features: 64
        activation: relu
      - type: linear
        in_features: 64
        out_features: 32
      # second to last layer is the policy layer
      - type: linear
        in_features: 32
        out_features: ${{snakepac.action_space}}
      # last layer is the value layer
      - type: linear
        in_features: 32
        out_features: 1

    dynamics:
      - type: linear
        in_features: 68
        out_features: 128
        activation: relu
      - type: linear
        in_features: 128
        out_features: 64
      # second to last layer is the hidden state layer
      - type: linear
        in_features: 64
        out_features: ${{snakepac.network.hidden_state_size}}
      # last layer is the reward layer
      - type: linear
        in_features: 64
        out_features: 1


  

riverraid:
  num_episodes: 100
  num_simulations: 100
  training_interval: 10
  batch_size: 32

  skip_frames: 4
  action_frames: 4
  mcts:
    num_searches: 50
    max_depth: 10
    ucb_constant: 1.0
    discount_factor: 0.95

logging:

network:
  # for snakepac
  iteration: ""
  representation:
  - type: linear
    in_features: "" # Will be set by the environment
    out_features: 
    activation: relu
  - type: linear
    in_features: 128
    out_features: 64

  prediction:
    - type: linear
      in_features: 64
      out_features: 64
      activation: relu
    - type: linear
      in_features: 64
      out_features: 10

  dynamics:
    - type: linear
      in_features: 68
      out_features: 128
      activation: relu
    - type: linear
      in_features: 128
      out_features: 64
