training:
  environment: 'snakepac' # 'snakepac' or other when implemented
  logging: True

snakepac:
  world_length: 10
  seed: 42

mcts:
  num_simulations: 100
  max_depth: 10
  ucb_constant: 1.0
  discount_factor: 0.95

logging: